name: Dart Release Workflow

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  Release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get

      - name: List all file
        shell: pwsh
        run: |
            Get-ChildItem -Path . -File

      - name: Build Windows Executable
        run: flutter build windows --release
        working-directory: ./

      - name: Zip data files
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path ${{github.ref_name}} -Force:$true
          Move-Item -Path ./chromedriver.exe -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/my_app.exe -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/data -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/url_launcher_windows_plugin.dll -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/screen_retriever_plugin.dll -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/auto_updater_windows_plugin.dll -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/flutter_windows.dll -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/window_manager_plugin.dll -Destination ${{github.ref_name}} -ErrorAction Stop
          Move-Item -Path ./build/windows/x64/runner/Release/WinSparkle.dll -Destination ${{github.ref_name}} -ErrorAction Stop
          Compress-Archive -Path ${{github.ref_name}}  -DestinationPath ./build/windows/x64/runner/Release/${{github.ref_name}}.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./chromedriver.exe
            ./build/windows/x64/runner/Release/WinSparkle.dll
            ./build/windows/x64/runner/Release/${{github.ref_name}}.zip